name: typos

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GitHub CLI
        run: sudo apt-get install gh
      - name: Run actions using diff_files
        run: |
          git diff --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}"
      - name: Writes changes in the local checkout
        uses: crate-ci/typos@master
        with:
          write_changes: true
