name: typos

on:
  pull_request:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Writes changes in the local checkout
        uses: crate-ci/typos@master
        with:
          write_changes: true
