name: typos

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitHub CLI
        run: sudo apt-get install gh
      - name: Run actions using diff_files
        id: diff_files
        run: |
          diffs=$(git diff "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" --no-ext-diff --unified=0 --exit-code -a --no-prefix | egrep '^\\+')
          echo "$diffs"
          echo "$diffs" > ./diffs.txt
      - name: Writes changes in the local checkout
        uses: crate-ci/typos@master
        with:
          files: ./diffs.txt
          write_changes: false
