name: typos

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitHub CLI
        run: sudo apt-get install gh
      - name: Run actions using diff_files
        id: diff_files
        run: |
          diff_files=$(git diff --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" \
            | tr "\n" " ")
          echo "DIFF_FILES=$diff_files" >> $GITHUB_OUTPUT
      - name: Writes changes in the local checkout
        uses: crate-ci/typos@master
        with:
          files: "${{ steps.diff_files.outputs.DIFF_FILES }}"
          write_changes: false
